version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    restart: always

  kafka:
    image: quay.io/debezium/kafka:2.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always

  db:
    image: quay.io/debezium/example-mysql:2.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.db
    ports:
      - 3306:3306

  connect:
    image: quay.io/debezium/connect:2.3
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - db
    restart: always

  mysqlterm:
    image: mysql:8.0
    restart: 'no'
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
    depends_on:
      - db
    command: >
      bash -c "
        while ! mysqladmin ping -hdb --silent; do
          sleep 1;
        done;
        mysql -uroot -p\"$$MYSQL_ROOT_PASSWORD\" -h db inventory
      "

